# Offense count: 2
Metrics/AbcSize:
  Max: 100

# Offense count: 16
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 250

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 50

## Offense count: 4
## Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'libraries/default_provider.rb'
    - 'libraries/default_resource.rb'
    - 'libraries/docker_provider.rb'
    - 'libraries/docker_resource.rb'
